name: dishank_dev_resume_website
description: A new Flutter project.

publish_to: "none"

version: 0.1.1+11

environment:
  sdk: ^3.1.5

dependencies:
  flutter:
    sdk: flutter

  google_fonts:
  url_launcher:
  firebase_core:
  firebase_database:
  web:
  # flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/img/
    - asset/img/bg/
    - asset/img/logo/
    - asset/icon/
